syntax = "proto3";

message Position {
  int32 x = 1;
  int32 y = 2;
}

enum ColorEnum {
    BLACK = 0;
    WHITE = 1;
    RED = 2;
    BLUE = 3;
    GREEN = 4;
    YELLOW = 5;
}

message Player {
  uint64 player_id = 1;
  Position position = 2;
  ColorEnum color = 3;
  uint64 nukes = 4;
  bool ready = 5;
}

message Movable {
  Position position = 1;
  Position vector = 2;
  string sprite = 3;
  string type = 4;
}

message Nuke {
  Position position = 1;
}

message Event {
  string event = 1;
  uint64 id = 2;
}

message Game {
  uint64 game_id = 1;
  bool debug = 2;
  bool started = 3;
  string game_mode = 50;

  map<uint64, Player> players = 4;
  uint64 player_to_move_id = 5;
  uint64 winner_id = 23;
  uint32 dice_pips = 6;

  repeated Movable movables = 7;
  repeated Nuke nukes = 8;
  repeated Event events = 9;

  uint64 nukes_used = 10;

  repeated ColorEnum taken_colors = 13;
  bool players_are_ready = 14;

  uint32 deg_board = 15;
  uint32 deg_color = 16;
  uint32 deg_pieces = 17;
  uint32 deg_dice = 18;
  uint32 deg_nuke_text = 19;
  uint32 deg_snakes_and_ladders = 20;
  uint32 deg_piece_shake = 21;
}
